branches: 
  - main
  - name: 'beta'
    prerelease: true
plugins:
- '@semantic-release/commit-analyzer'
- '@semantic-release/release-notes-generator'
# - '@semantic-release/git'
- '@semantic-release/github'
- - '@semantic-release/npm'
  - npmPublish: true
analyzeCommits:
  - path: '@semantic-release/commit-analyzer'
    releaseRules:
    - type: 'feat'
      release: 'minor'
    - type: 'fix'
      release: 'patch'
    - type: 'patch'
      release: 'patch'
    - type: 'minor'
      release: 'minor'
    - type: 'breaking'
      release: 'major'
    - type: 'major'
      release: 'major'